//
// V0UserProfileDataModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0UserProfileDataModel: Codable, Hashable {
    public var avatarUrl: String?
    public var createdAt: String?
    public var dataId: Int?
    public var email: String
    public var hasUsedOrganizationTrial: Bool?
    public var paymentProcessor: String?
    public var slug: String?
    public var unconfirmedEmail: String?
    public var username: String?
}
