//
// V0AddOnAppResponseItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0AddOnAppResponseItemModel: Codable {

    public let icon: String?
    public let plan: AddonsPlan?
    public let planStartedAt: String?
    public let slug: String?
    public let title: String?

    public init(icon: String? = nil, plan: AddonsPlan? = nil, planStartedAt: String? = nil, slug: String? = nil, title: String? = nil) {
        self.icon = icon
        self.plan = plan
        self.planStartedAt = planStartedAt
        self.slug = slug
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case icon
        case plan
        case planStartedAt = "plan_started_at"
        case slug
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(planStartedAt, forKey: .planStartedAt)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(title, forKey: .title)
    }
}
