//
// V0AppRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0AppRespModel: Codable {

    public let slug: String?
    public let status: String?

    public init(slug: String? = nil, status: String? = nil) {
        self.slug = slug
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(status, forKey: .status)
    }
}
