//
// V0AppWebhookResponseItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0AppWebhookResponseItemModel: Codable {

    public let createdAt: String?
    public let events: [String]?
    public let headers: [Int]?
    public let registeredByAddon: Bool?
    public let slug: String?
    public let updatedAt: String?
    public let url: String?

    public init(createdAt: String? = nil, events: [String]? = nil, headers: [Int]? = nil, registeredByAddon: Bool? = nil, slug: String? = nil, updatedAt: String? = nil, url: String? = nil) {
        self.createdAt = createdAt
        self.events = events
        self.headers = headers
        self.registeredByAddon = registeredByAddon
        self.slug = slug
        self.updatedAt = updatedAt
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case events
        case headers
        case registeredByAddon = "registered_by_addon"
        case slug
        case updatedAt = "updated_at"
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(registeredByAddon, forKey: .registeredByAddon)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(url, forKey: .url)
    }
}
