//
// V0BuildShowResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0BuildShowResponseModel: Codable, Sendable {

    public var data: BuildResponseItemModel

    public init(data: BuildResponseItemModel) {
        self.data = data
    }
}
