//
// V0CommitPaths.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0CommitPaths: Codable {

    public let added: [String]?
    public let modified: [String]?
    public let removed: [String]?

    public init(added: [String]? = nil, modified: [String]? = nil, removed: [String]? = nil) {
        self.added = added
        self.modified = modified
        self.removed = removed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case added
        case modified
        case removed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(added, forKey: .added)
        try container.encodeIfPresent(modified, forKey: .modified)
        try container.encodeIfPresent(removed, forKey: .removed)
    }
}
