//
// V0AvatarCandidateCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0AvatarCandidateCreateParams: Codable, Hashable {

    public var filename: String
    public var filesize: Int

    public init(filename: String, filesize: Int) {
        self.filename = filename
        self.filesize = filesize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filename
        case filesize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filename, forKey: .filename)
        try container.encode(filesize, forKey: .filesize)
    }
}
