//
// V0BuildCertificateUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0BuildCertificateUpdateParams: Codable, Hashable {

    public var certificatePassword: String?
    public var isExpose: Bool?
    public var isProtected: Bool?
    public var processed: Bool?

    public init(certificatePassword: String? = nil, isExpose: Bool? = nil, isProtected: Bool? = nil, processed: Bool? = nil) {
        self.certificatePassword = certificatePassword
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificatePassword = "certificate_password"
        case isExpose = "is_expose"
        case isProtected = "is_protected"
        case processed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificatePassword, forKey: .certificatePassword)
        try container.encodeIfPresent(isExpose, forKey: .isExpose)
        try container.encodeIfPresent(isProtected, forKey: .isProtected)
        try container.encodeIfPresent(processed, forKey: .processed)
    }
}
