//
// V0UserPlanDataModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V0UserPlanDataModel: Codable, Hashable {

    public var currentPlan: V0PlanDataModel?
    public var pendingPlan: V0PlanDataModel?
    public var trialExpiresAt: String?

    public init(currentPlan: V0PlanDataModel? = nil, pendingPlan: V0PlanDataModel? = nil, trialExpiresAt: String? = nil) {
        self.currentPlan = currentPlan
        self.pendingPlan = pendingPlan
        self.trialExpiresAt = trialExpiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPlan = "current_plan"
        case pendingPlan = "pending_plan"
        case trialExpiresAt = "trial_expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentPlan, forKey: .currentPlan)
        try container.encodeIfPresent(pendingPlan, forKey: .pendingPlan)
        try container.encodeIfPresent(trialExpiresAt, forKey: .trialExpiresAt)
    }
}
