//
// NullsString.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NullsString: Codable {

    public var string: String?
    /** Valid is true if String is not NULL */
    public var valid: Bool?

    public init(string: String? = nil, valid: Bool? = nil) {
        self.string = string
        self.valid = valid
    }


}
