//
// V0AppAddOnsListResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppAddOnsListResponseModel: Codable {

    public var data: [V0AppAddOnResponseItemModel]?

    public init(data: [V0AppAddOnResponseItemModel]? = nil) {
        self.data = data
    }


}
