//
// V0AppWebhookDeletedResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppWebhookDeletedResponseModel: Codable {

    public var data: V0AppWebhookResponseItemModel?

    public init(data: V0AppWebhookResponseItemModel? = nil) {
        self.data = data
    }


}
