//
// V0BuildCertificateUploadParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildCertificateUploadParams: Codable {

    public var uploadFileName: String
    public var uploadFileSize: Int

    public init(uploadFileName: String, uploadFileSize: Int) {
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
    }

    public enum CodingKeys: String, CodingKey { 
        case uploadFileName = "upload_file_name"
        case uploadFileSize = "upload_file_size"
    }

}
