//
// V0ProvisionProfileResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ProvisionProfileResponseModel: Codable {

    public var data: V0ProvisionProfileResponseItemModel?

    public init(data: V0ProvisionProfileResponseItemModel? = nil) {
        self.data = data
    }


}
