//
// V0TestDeviceListResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0TestDeviceListResponseModel: Codable {

    public var data: [V0TestDeviceResponseItemModel]?

    public init(data: [V0TestDeviceResponseItemModel]? = nil) {
        self.data = data
    }


}
