//
// V0TestDeviceResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0TestDeviceResponseItemModel: Codable {

    public var deviceId: String?
    public var deviceType: String?
    public var owner: String?

    public init(deviceId: String? = nil, deviceType: String? = nil, owner: String? = nil) {
        self.deviceId = deviceId
        self.deviceType = deviceType
        self.owner = owner
    }

    public enum CodingKeys: String, CodingKey { 
        case deviceId = "device_id"
        case deviceType = "device_type"
        case owner
    }

}
