//
// V0UserPlanRespModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0UserPlanRespModel: Codable {

    public var data: V0UserPlanDataModel?

    public init(data: V0UserPlanDataModel? = nil) {
        self.data = data
    }


}
