//
// V0AddonsShowResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AddonsShowResponseModel: Codable {

    public var data: AddonsAddon?

    public init(data: AddonsAddon? = nil) {
        self.data = data
    }


}
