//
// V0AppWebhookUpdateParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppWebhookUpdateParams: Codable {

    public var events: [String]
    public var headers: [Int]?
    public var url: String

    public init(events: [String], headers: [Int]? = nil, url: String) {
        self.events = events
        self.headers = headers
        self.url = url
    }


}
