//
// V0AppResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppResponseItemModel: Codable {

    public var avatarUrl: String?
    public var isDisabled: Bool?
    public var isPublic: Bool?
    public var owner: V0OwnerAccountResponseModel?
    public var projectType: String?
    public var provider: String?
    public var repoOwner: String?
    public var repoSlug: String?
    public var repoUrl: String?
    public var slug: String?
    public var status: Int?
    public var title: String?

    public init(avatarUrl: String? = nil, isDisabled: Bool? = nil, isPublic: Bool? = nil, owner: V0OwnerAccountResponseModel? = nil, projectType: String? = nil, provider: String? = nil, repoOwner: String? = nil, repoSlug: String? = nil, repoUrl: String? = nil, slug: String? = nil, status: Int? = nil, title: String? = nil) {
        self.avatarUrl = avatarUrl
        self.isDisabled = isDisabled
        self.isPublic = isPublic
        self.owner = owner
        self.projectType = projectType
        self.provider = provider
        self.repoOwner = repoOwner
        self.repoSlug = repoSlug
        self.repoUrl = repoUrl
        self.slug = slug
        self.status = status
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrl = "avatar_url"
        case isDisabled = "is_disabled"
        case isPublic = "is_public"
        case owner
        case projectType = "project_type"
        case provider
        case repoOwner = "repo_owner"
        case repoSlug = "repo_slug"
        case repoUrl = "repo_url"
        case slug
        case status
        case title
    }

}
