//
// V0AppWebhookCreateParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppWebhookCreateParams: Codable {

    public var events: [String]
    public var headers: [Int]?
    public var secret: String
    public var url: String

    public init(events: [String], headers: [Int]? = nil, secret: String, url: String) {
        self.events = events
        self.headers = headers
        self.secret = secret
        self.url = url
    }


}
