//
// V0AppleAPICredentialsListResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppleAPICredentialsListResponse: Codable {

    public var data: [V0AppleAPICredentialResponseItem]?

    public init(data: [V0AppleAPICredentialResponseItem]? = nil) {
        self.data = data
    }


}
