//
// V0AppUploadParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppUploadParams: Codable {

    /** The slug of the owner of the repository at the git provider */
    public var gitOwner: String
    /** The slug of the repository at the git provider */
    public var gitRepoSlug: String
    /** If &#x60;true&#x60; then the repository visibility setting will be public, in case of &#x60;false&#x60; it will be private */
    public var isPublic: Bool
    /** The git provider you are using, it can be &#x60;github&#x60;, &#x60;bitbucket&#x60;, &#x60;gitlab&#x60;, &#x60;gitlab-self-hosted&#x60; or &#x60;custom&#x60; */
    public var provider: String
    /** The URL of your repository */
    public var repoUrl: String
    /** It has to be provided by legacy reasons and has to have the &#x60;git&#x60; value */
    public var type: String

    public init(gitOwner: String, gitRepoSlug: String, isPublic: Bool, provider: String, repoUrl: String, type: String) {
        self.gitOwner = gitOwner
        self.gitRepoSlug = gitRepoSlug
        self.isPublic = isPublic
        self.provider = provider
        self.repoUrl = repoUrl
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case gitOwner = "git_owner"
        case gitRepoSlug = "git_repo_slug"
        case isPublic = "is_public"
        case provider
        case repoUrl = "repo_url"
        case type
    }

}
