//
// V0ArtifactDeleteResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ArtifactDeleteResponseModel: Codable {

    public var data: V0ArtifactResponseItemModel?

    public init(data: V0ArtifactResponseItemModel? = nil) {
        self.data = data
    }


}
