//
// V0AvatarCandidateCreateResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AvatarCandidateCreateResponseItem: Codable, Hashable {

    public var filename: String?
    public var filesize: Int?
    public var slug: String?
    public var uploadUrl: String?

    public init(filename: String? = nil, filesize: Int? = nil, slug: String? = nil, uploadUrl: String? = nil) {
        self.filename = filename
        self.filesize = filesize
        self.slug = slug
        self.uploadUrl = uploadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filename
        case filesize
        case slug
        case uploadUrl = "upload_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filename, forKey: .filename)
        try container.encodeIfPresent(filesize, forKey: .filesize)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(uploadUrl, forKey: .uploadUrl)
    }
}

