//
// V0BuildTriggerParamsHookInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildTriggerParamsHookInfo: Codable {

    /** Should be \&quot;bitrise\&quot; */
    public var type: String?

    public init(type: String? = nil) {
        self.type = type
    }


}
