//
// V0BuildRequestResponseItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildRequestResponseItemModel: Codable, Hashable {

    public var buildParams: [Int]?
    public var createdAt: String?
    public var pullRequestUrl: String?
    public var slug: String?

    public init(buildParams: [Int]? = nil, createdAt: String? = nil, pullRequestUrl: String? = nil, slug: String? = nil) {
        self.buildParams = buildParams
        self.createdAt = createdAt
        self.pullRequestUrl = pullRequestUrl
        self.slug = slug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case buildParams = "build_params"
        case createdAt = "created_at"
        case pullRequestUrl = "pull_request_url"
        case slug
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(buildParams, forKey: .buildParams)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(pullRequestUrl, forKey: .pullRequestUrl)
        try container.encodeIfPresent(slug, forKey: .slug)
    }
}

