//
// V0FindAvatarCandidateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0FindAvatarCandidateResponse: Codable {

    public var data: [V0FindAvatarCandidateResponseItem]?

    public init(data: [V0FindAvatarCandidateResponseItem]? = nil) {
        self.data = data
    }


}
