//
// V0OrganizationListRespModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0OrganizationListRespModel: Codable {

    public var data: [V0OrganizationDataModel]?

    public init(data: [V0OrganizationDataModel]? = nil) {
        self.data = data
    }


}
