//
// V0OrganizationDataModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0OrganizationDataModel: Codable {

    public var avatarIconUrl: String?
    public var concurrencyCount: Int?
    public var name: String?
    public var owners: [V0OrganizationOwner]?
    public var slug: String?

    public init(avatarIconUrl: String? = nil, concurrencyCount: Int? = nil, name: String? = nil, owners: [V0OrganizationOwner]? = nil, slug: String? = nil) {
        self.avatarIconUrl = avatarIconUrl
        self.concurrencyCount = concurrencyCount
        self.name = name
        self.owners = owners
        self.slug = slug
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarIconUrl = "avatar_icon_url"
        case concurrencyCount = "concurrency_count"
        case name
        case owners
        case slug
    }

}
