//
// V0ProjectFileStorageUploadParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ProjectFileStorageUploadParams: Codable {

    public var uploadFileName: String
    public var uploadFileSize: Int
    public var userEnvKey: String

    public init(uploadFileName: String, uploadFileSize: Int, userEnvKey: String) {
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
        self.userEnvKey = userEnvKey
    }

    public enum CodingKeys: String, CodingKey { 
        case uploadFileName = "upload_file_name"
        case uploadFileSize = "upload_file_size"
        case userEnvKey = "user_env_key"
    }

}
