//
// V0UserProfileDataModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0UserProfileDataModel: Codable {

    public var avatarUrl: String?
    public var createdAt: String?
    public var dataId: Int?
    public var email: String
    public var hasUsedOrganizationTrial: Bool?
    public var paymentProcessor: String?
    public var slug: String?
    public var unconfirmedEmail: String?
    public var username: String

    public init(avatarUrl: String? = nil, createdAt: String? = nil, dataId: Int? = nil, email: String = "", hasUsedOrganizationTrial: Bool? = nil, paymentProcessor: String? = nil, slug: String? = nil, unconfirmedEmail: String? = nil, username: String = "") {
        self.avatarUrl = avatarUrl
        self.createdAt = createdAt
        self.dataId = dataId
        self.email = email
        self.hasUsedOrganizationTrial = hasUsedOrganizationTrial
        self.paymentProcessor = paymentProcessor
        self.slug = slug
        self.unconfirmedEmail = unconfirmedEmail
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrl = "avatar_url"
        case createdAt = "created_at"
        case dataId = "data_id"
        case email
        case hasUsedOrganizationTrial = "has_used_organization_trial"
        case paymentProcessor = "payment_processor"
        case slug
        case unconfirmedEmail = "unconfirmed_email"
        case username
    }

}
