//
// AndroidKeystoreFileAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import Models


open class AndroidKeystoreFileAPI {
    /**
     Create an Android keystore file

     - parameter body: (body) Android keystore file parameters 
     - parameter appSlug: (path) App slug 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func androidKeystoreFileCreate(body: V0AndroidKeystoreFileUploadParams, appSlug: String, completion: @escaping ((_ data: V0ProjectFileStorageResponseModel?,_ error: Error?) -> Void)) {
        androidKeystoreFileCreateWithRequestBuilder(body: body, appSlug: appSlug).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create an Android keystore file
     - POST /apps/{app-slug}/android-keystore-files

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : {
    "processed" : true,
    "download_url" : "download_url",
    "is_expose" : true,
    "upload_file_name" : "upload_file_name",
    "upload_url" : "upload_url",
    "upload_file_size" : 6,
    "user_env_key" : "user_env_key",
    "exposed_meta_datastore" : [ 0, 0 ],
    "is_protected" : true,
    "slug" : "slug"
  }
}}]
     - parameter body: (body) Android keystore file parameters 
     - parameter appSlug: (path) App slug 

     - returns: RequestBuilder<V0ProjectFileStorageResponseModel> 
     */
    open class func androidKeystoreFileCreateWithRequestBuilder(body: V0AndroidKeystoreFileUploadParams, appSlug: String) -> RequestBuilder<V0ProjectFileStorageResponseModel> {
        var path = "/apps/{app-slug}/android-keystore-files"
        let appSlugPreEscape = "\(appSlug)"
        let appSlugPostEscape = appSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{app-slug}", with: appSlugPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<V0ProjectFileStorageResponseModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Get a list of the android keystore files

     - parameter appSlug: (path) App slug 
     - parameter next: (query) Slug of the first android keystore file in the response (optional)
     - parameter limit: (query) Max number of build certificates per page is 50. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func androidKeystoreFileList(appSlug: String, next: String? = nil, limit: Int? = nil, completion: @escaping ((_ data: V0ProjectFileStorageListResponseModel?,_ error: Error?) -> Void)) {
        androidKeystoreFileListWithRequestBuilder(appSlug: appSlug, next: next, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a list of the android keystore files
     - GET /apps/{app-slug}/android-keystore-files

     - API Key:
       - type: apiKey Bitrise-Addon-Auth-Token 
       - name: AddonAuthToken
     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "processed" : true,
    "download_url" : "download_url",
    "is_expose" : true,
    "upload_file_name" : "upload_file_name",
    "upload_url" : "upload_url",
    "upload_file_size" : 6,
    "user_env_key" : "user_env_key",
    "exposed_meta_datastore" : [ 0, 0 ],
    "is_protected" : true,
    "slug" : "slug"
  }, {
    "processed" : true,
    "download_url" : "download_url",
    "is_expose" : true,
    "upload_file_name" : "upload_file_name",
    "upload_url" : "upload_url",
    "upload_file_size" : 6,
    "user_env_key" : "user_env_key",
    "exposed_meta_datastore" : [ 0, 0 ],
    "is_protected" : true,
    "slug" : "slug"
  } ],
  "paging" : {
    "next" : "next",
    "page_item_limit" : 6,
    "total_item_count" : 1
  }
}}]
     - parameter appSlug: (path) App slug 
     - parameter next: (query) Slug of the first android keystore file in the response (optional)
     - parameter limit: (query) Max number of build certificates per page is 50. (optional)

     - returns: RequestBuilder<V0ProjectFileStorageListResponseModel> 
     */
    open class func androidKeystoreFileListWithRequestBuilder(appSlug: String, next: String? = nil, limit: Int? = nil) -> RequestBuilder<V0ProjectFileStorageListResponseModel> {
        var path = "/apps/{app-slug}/android-keystore-files"
        let appSlugPreEscape = "\(appSlug)"
        let appSlugPostEscape = appSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{app-slug}", with: appSlugPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "next": next, 
                        "limit": limit?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<V0ProjectFileStorageListResponseModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
