//
// PipelinesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import Models


open class PipelinesAPI {
    /**
     List all pipelines of an app

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func pipelineList(completion: @escaping ((_ data: V0BuildListResponseModel?,_ error: Error?) -> Void)) {
        pipelineListWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List all pipelines of an app
     - GET /apps/{app-slug}/pipelines

     - API Key:
       - type: apiKey Bitrise-Addon-Auth-Token 
       - name: AddonAuthToken
     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : [ {
    "environment_prepare_finished_at" : "environment_prepare_finished_at",
    "finished_at" : "finished_at",
    "abort_reason" : {
      "valid" : true,
      "string" : "string"
    },
    "slug" : "slug",
    "original_build_params" : [ 1, 1 ],
    "is_processed" : true,
    "triggered_at" : "triggered_at",
    "is_on_hold" : true,
    "started_on_worker_at" : "started_on_worker_at",
    "pull_request_id" : 5,
    "credit_cost" : {
      "valid" : true,
      "int64" : 6
    },
    "triggered_workflow" : "triggered_workflow",
    "build_number" : 0,
    "status_text" : "status_text",
    "status" : 5
  }, {
    "environment_prepare_finished_at" : "environment_prepare_finished_at",
    "finished_at" : "finished_at",
    "abort_reason" : {
      "valid" : true,
      "string" : "string"
    },
    "slug" : "slug",
    "original_build_params" : [ 1, 1 ],
    "is_processed" : true,
    "triggered_at" : "triggered_at",
    "is_on_hold" : true,
    "started_on_worker_at" : "started_on_worker_at",
    "pull_request_id" : 5,
    "credit_cost" : {
      "valid" : true,
      "int64" : 6
    },
    "triggered_workflow" : "triggered_workflow",
    "build_number" : 0,
    "status_text" : "status_text",
    "status" : 5
  } ],
  "paging" : {
    "next" : "next",
    "page_item_limit" : 6,
    "total_item_count" : 1
  }
}}]

     - returns: RequestBuilder<V0BuildListResponseModel> 
     */
    open class func pipelineListWithRequestBuilder() -> RequestBuilder<V0BuildListResponseModel> {
        let path = "/apps/{app-slug}/pipelines"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<V0BuildListResponseModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
