//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class UserAPI {
    /**
     The active addon tokens of the user

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userAddonTokens(completion: @escaping ((_ data: [String]?,_ error: Error?) -> Void)) {
        userAddonTokensWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     The active addon tokens of the user
     - GET /me/addon-tokens

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example=[ "", "" ]}]

     - returns: RequestBuilder<[String]> 
     */
    open class func userAddonTokensWithRequestBuilder() -> RequestBuilder<[String]> {
        let path = "/me/addon-tokens"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[String]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Removes an active addon token of the user

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userAddonTokensDelete(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        userAddonTokensDeleteWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Removes an active addon token of the user
     - DELETE /me/addon-tokens/{addon-id}

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken

     - returns: RequestBuilder<Void> 
     */
    open class func userAddonTokensDeleteWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/me/addon-tokens/{addon-id}"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     The subscription plan of the user

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userPlan(completion: @escaping ((_ data: V0UserPlanRespModel?,_ error: Error?) -> Void)) {
        userPlanWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     The subscription plan of the user
     - GET /me/plan

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : {
    "current_plan" : {
      "expires_at" : "expires_at",
      "price" : {
        "valid" : true,
        "int64" : 6
      },
      "name" : "name",
      "id" : "id",
      "container_count" : 0
    },
    "trial_expires_at" : "trial_expires_at"
  }
}}]

     - returns: RequestBuilder<V0UserPlanRespModel> 
     */
    open class func userPlanWithRequestBuilder() -> RequestBuilder<V0UserPlanRespModel> {
        let path = "/me/plan"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<V0UserPlanRespModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get your profile data

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userProfile(completion: @escaping ((_ data: V0UserProfileRespModel?,_ error: Error?) -> Void)) {
        userProfileWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get your profile data
     - GET /me

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : {
    "unconfirmed_email" : "unconfirmed_email",
    "avatar_url" : "avatar_url",
    "data_id" : 0,
    "created_at" : "created_at",
    "payment_processor" : "payment_processor",
    "email" : "email",
    "slug" : "slug",
    "has_used_organization_trial" : true,
    "username" : "username"
  }
}}]

     - returns: RequestBuilder<V0UserProfileRespModel> 
     */
    open class func userProfileWithRequestBuilder() -> RequestBuilder<V0UserProfileRespModel> {
        let path = "/me"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<V0UserProfileRespModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get a specific user

     - parameter userSlug: (path) User slug 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userShow(userSlug: String, completion: @escaping ((_ data: V0UserProfileRespModel?,_ error: Error?) -> Void)) {
        userShowWithRequestBuilder(userSlug: userSlug).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a specific user
     - GET /users/{user-slug}

     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - examples: [{contentType=application/json, example={
  "data" : {
    "unconfirmed_email" : "unconfirmed_email",
    "avatar_url" : "avatar_url",
    "data_id" : 0,
    "created_at" : "created_at",
    "payment_processor" : "payment_processor",
    "email" : "email",
    "slug" : "slug",
    "has_used_organization_trial" : true,
    "username" : "username"
  }
}}]
     - parameter userSlug: (path) User slug 

     - returns: RequestBuilder<V0UserProfileRespModel> 
     */
    open class func userShowWithRequestBuilder(userSlug: String) -> RequestBuilder<V0UserProfileRespModel> {
        var path = "/users/{user-slug}"
        let userSlugPreEscape = "\(userSlug)"
        let userSlugPostEscape = userSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{user-slug}", with: userSlugPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<V0UserProfileRespModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
